### ISSUE TITLE
Values read from DB need escaping in "And I should have" statement

### ISSUE THREAD

**Issue by radeasy** [forceedge01/genesis-behat-sql-extension#6]
e.g. for input value: Last1 Name With 25 Char's 
note: apostrophe above

You need to escape it like below:
And I should have a "woody_crm.users" with "id:{woody_crm.users_id},forename:First Name With 25 Char\'s,lastname:Last1 Name With 25 Char\'s"

**Comment by forceedge01** [comment]
Sure will get this sorted as soon as possible. Thanks for logging the issue.

**Comment by forceedge01** [comment]
In PR https://github.com/forceedge01/genesis-behat-sql-extension/pull/7

**Comment by forceedge01** [comment]
Merged.
